### ISSUE TITLE
Inappropriate error handling: Invalid country code country codes

### ISSUE THREAD

**Issue by AuroraDysis** [AuroPick/epic-free-games#1]
In the current code, there are the following lines

https://github.com/AuroPick/epic-free-games/blob/f76dc3730dae62f50be0b0d86f98e5b67456cda3/src/index.ts#L133-L136

But this error is not correct, data?.errors is often not empty.
I run getGames every 5 minutes and here is my log.

![image](https://user-images.githubusercontent.com/13709836/145639832-dbe71d3f-a9ea-466c-8d1f-44525053c7ad.png)

**Comment by AuroPick** [comment]
Hi @AuroraDysis 

Thanks for feedback.

Can you share your code?

**Comment by AuroraDysis** [comment]
```ts
import { getGames } from "epic-free-games";
const games = getGames("US");
```

My code is very simple...

**Comment by AuroPick** [comment]
This function returns promise. Are you using then or await?

Also you don't need to pass "US" it is default value.

Anyway try with new version. You can see server response.

**Comment by AuroPick** [comment]
> ```ts
> import { getGames } from "epic-free-games";
> const games = getGames("US");
> ```
> 
> My code is very simple...

Can you get response on local. Maybe epic games servers blocking you for too much requests

**Comment by AuroraDysis** [comment]
Sure, I can. As you can see from the logs, it works well for most of the day.

```
Maybe epic games servers blocking you for too much requests
```

Maybe...

**Comment by AuroPick** [comment]
Did you try with new version. You can see server response now.

**Comment by AuroraDysis** [comment]
Thanks. It looks good to me. I have updated the package and will collect enough logs in the next few days.

**Comment by AuroraDysis** [comment]
With the latest version of the package, I logged exceptions as following
![image](https://user-images.githubusercontent.com/13709836/146213390-90e64e08-916f-40cd-a67d-a0ecf0ef146a.png)
![image](https://user-images.githubusercontent.com/13709836/146213612-3ea6790b-66b4-4fd2-84f2-8265c0d9adbd.png)
It appears several times a week, so I think it's better to throw a proper exception for it.

**Comment by AuroPick** [comment]
> With the latest version of the package, I logged exceptions as following ![image](https://user-images.githubusercontent.com/13709836/146213390-90e64e08-916f-40cd-a67d-a0ecf0ef146a.png) ![image](https://user-images.githubusercontent.com/13709836/146213612-3ea6790b-66b4-4fd2-84f2-8265c0d9adbd.png) It appears several times a week, so I think it's better to throw a proper exception for it.

This is happening because of Epic servers. I have no control on this. Maybe you want to update new version.

**Comment by AuroraDysis** [comment]
That's exactly what I want. Thanks.
