### ISSUE TITLE
Support other countries

### ISSUE THREAD

**Issue by rthm93** [AuroPick/epic-free-games#13]
Hi, 

I am wondering why are we limiting the country enum to the selected few only? Are there different schemas for different countries?

**Comment by AuroPick** [comment]
Hi @rthm93 ,

There is no documentation about this Epic Games api. I have tested few popular countries. You can check other countries and open pr. I can merge it next release.

**Comment by AuroPick** [comment]
Price changes by country

**Comment by AuroPick** [comment]
Closing this.
