### ISSUE TITLE
Expiry Date

### ISSUE THREAD

**Issue by OpenSauce** [AuroPick/epic-free-games#2]
Love the work, using it in my Discord bot as we speak! 

Is there anyway of getting the date the offers expire? Looking at it I know you can usee the nexts effectiveDate but as of right now I'm not getting anything returned there.

Thanks a lot :)

**Comment by AuroPick** [comment]
Hi

Thank you for your interest

https://github.com/AuroPick/epic-free-games/blob/e52b94156542e3fb21ce5a84ec93576b77250f62/src/index.ts#L56-L68

There is a endDate key you can access it like that

```js
currents[0].promotions.promotionalOffers[0].promotionalOffers[0].endDate
```

**Comment by OpenSauce** [comment]
Awesome, thanks 😃
