### ISSUE TITLE
"Failed to challenge captcha, please try again later"

### ISSUE THREAD

**Issue by jbking93-git** [AuroPick/epic-free-games#20]
Hi there,

first of all, thanks for this wonderful tool! It's been working great for the past few months.
However, recently (the past 2 weeks, maybe 3) I have been unable to successfully resolve a captcha request from this script and have had to claim my games manually via the epic client each week.

- I'm running this in a docker container on my Unraid box. 
- The container is surfaced to the outside world via reverse proxy (`nginx`) and SSL cert via letsencrypt (`swag` docker container)
- I have notifications setup to both Discord and a HTTPS webhook attached to home assistant.
- I'm in Australia and typically receive a captcha request every Friday morning when the script runs to check for this week's free game.
- Everything about the process works the same as it always has - the puppeteer portal appears to work fine, I get prompted with the captcha and resolve it, click proceed and then am presented with the Epic Store "checkout" page, and an error "Failed to challenge captcha, please try again later" in red. (attached image)
![image](https://github.com/AuroPick/epic-free-games/assets/63386355/a9b218d4-1fda-4575-a162-bd36f0118c5d)

- I've tried actioning the request on my phone and desktop - same results.
- I haven't changed anything to do with this docker, my reverse proxy, or related systems that would've caused this, afaik.

I hope I've provided enough information. Thanks in advance.

Best,

Joshua

**Comment by AuroPick** [comment]
Hi Joshua,

So sorry for late reply. I didn't see your issue.

My library does not provide any 'claim' feature. This library just for fetching games from Epic Games API.

Are you sure you opened this issue to correct repo

**Comment by jbking93-git** [comment]
> Hi Joshua,
> 
> So sorry for late reply. I didn't see your issue.
> 
> My library does not provide any 'claim' feature. This library just for fetching games from Epic Games API.
> 
> Are you sure you opened this issue to correct repo

I'm so sorry. It does appear I've raised this issue in the wrong repo. My apologies.. not sure how I got here in the first place!
