### ISSUE TITLE
Price is always 0

### ISSUE THREAD

**Issue by alvaroelpob** [AuroPick/epic-free-games#25]
So im using the module to get info but the object currentGames[?].price does not show a price. The attachment shows Farming Simulator 22 which originally costs 19,99$ and the package returns 0.

Apart from this the module is fast and very user-friendly

**Comment by AuroPick** [comment]
Hi @newalvaro9 

Sorry for late response. This wrapper provides typescript definitions

https://github.com/AuroPick/epic-free-games/blob/8e4b0641fb2c428a5ba5008e4cbe108e88ca8927/src/core/types/offer-game.type.ts#L36-L53

There should be `discountPrice` and `originalPrice` variables for each offer.

You can access them like this:
```js
currentGames[0]?.price.totalPrice.discountPrice
currentGames[0]?.price.totalPrice.originalPrice
```
![image](https://github.com/AuroPick/epic-free-games/assets/53499802/264ac600-8256-41c9-a446-1f7052628180)
