### ISSUE TITLE
Empty array Nexts

### ISSUE THREAD

**Issue by OfficialRDB** [AuroPick/epic-free-games#3]
The array returns empty for the nexts game(s), while the game that is upcoming is under current already.
How can I fix that ?

**Comment by AuroPick** [comment]
Hey thanks for feedback.

Please check new version. It should work.

It is major version.

You need to change variables.

```js
currents -> currentGames
nexts -> nextGames
```

**Comment by OfficialRDB** [comment]
Perfect! Works. Thanks for the reply and the quick fix.
