### ISSUE TITLE
Games display

### ISSUE THREAD

**Issue by OfficialRDB** [AuroPick/epic-free-games#5]
This week they have 3 FREE games but it only outputs 2.
https://www.epicgames.com/store/en-US/

[Epic Slayer Kit](https://www.epicgames.com/store/en-US/p/dauntless--epic-slayer-kit)
Is not in the output.

**Comment by AuroPick** [comment]
It is a DLC. 

That's why it doesn't show up.

Maybe I can add an option to include all offers.

**Comment by OfficialRDB** [comment]
If you have time and want to add it, Yes please.
