### ISSUE TITLE
Game URL

### ISSUE THREAD

**Issue by DuckySoLucky** [AuroPick/epic-free-games#8]
Heya, I have a question. How would I get url to the game?
I have tried using `res.currentGames[i].productSlug` and `res.currentGames[i].customAttributes[2].value` but then I have realized not every game has that value which I can use in the url.  Am I missing something or? Thanks

**Comment by AuroPick** [comment]
Hi

I don't know how Epic Games manage their slugs but looks like catalogNs object has pageSlug for every offer.

**Comment by DuckySoLucky** [comment]
Thanks it works.
